name: Deploy to Production

on:
  push:
    branches:
      - master

jobs:
  call-template:
    uses: ./.github/workflows/deploy-template.yml
    with:
      environment: production
      secrets_path: secrets/production
