name: Deploy to Staging

on:
    push:
        branches:
            - staging

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Create .env file from GitHub secret
              run: |
                  echo "${{ secrets.ENV_STAGING }}" > .env

            - name: Execute deployment commands over SSH
              uses: appleboy/ssh-action@v1.2.0
              with:
                  host: "${{ secrets.SSH_HOST_STAGING }}"
                  username: "${{ secrets.SSH_USER_STAGING }}"
                  password: "${{ secrets.SSH_PASSWORD_STAGING }}"
                  port: 22
                  script: |
                    echo "host_is : ${{ secrets.SSH_HOST_STAGING }}"
                    cd /var/www/backend_v2
                    git checkout staging
                    git pull origin staging
                    composer install --no-dev --optimize-autoloader
                    php artisan optimize:clear
                    php artisan migrate --force
                    php artisan queue:restart
                    php artisan octane:reload
                    php artisan optimize
                    echo "✅ Deployment completed successfully!"
