name: Deploy to Staging

on:
  push:
    branches:
      - staging

jobs:
  call-deploy-template:
    uses: ./.github/workflows/deploy-template.yml
    with:
      environment: staging
      secrets_path: secrets/staging
    secrets: inherit
